version: '3.8'

services:

  mariadb:
    image: mariadb:10.7.1
    container_name: mariadb
    ports: 
      - "3306:3306"
    environment:
      MARIADB_USER: gvendas
      MARIADB_PASSWORD: prmorais13
      MARIADB_ROOT_PASSWORD: Paulo1313
      MARIADB_DATABASE: gvendas_db

  jaeger:
    image: jaegertracing/all-in-one:1.28
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  prometheus:
    image: prom/prometheus:v2.31.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:etc/prometheus/prometheus.yml
    command:
      - "--config-file=etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:8.3.0
    container_name: grafana
    ports:
      - "3000:3000"