version: '3.8'

services:

  mariadb:
    image: mariadb:10.7.1
    container_name: mariadb
    ports: 
      - "3306:3306"
    environment:
      MARIADB_USER: gvendas
      MARIADB_PASSWORD: prmorais13
      MARIADB_ROOT_PASSWORD: Paulo1313
      MARIADB_DATABASE: gvendas_db

  jaeger:
    image: jaegertracing/all-in-one:1.28
    container_name: jaeger
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"